# Generated by Django 5.0 on 2024-06-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='torrent_url',
            field=models.CharField(default='about:blank', help_text='Magnet URL', max_length=200),
        ),
    ]
