# Generated by Django 5.0 on 2024-08-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_blogpost_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(help_text='Markdown')),
            ],
            options={
                'ordering': ['question'],
            },
        ),
    ]
