# Generated by Django 5.0 on 2024-08-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0005_questionanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='order',
            field=models.PositiveSmallIntegerField(default=100),
            preserve_default=False,
        ),
    ]
