# Generated by Django 5.0 on 2024-09-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0006_alter_questionanswer_options_questionanswer_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('form_factor', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-create_date']},
        ),
    ]
