# Generated by Django 5.0 on 2025-07-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0008_alter_hardwaredevice_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('answer', models.TextField(help_text='Markdown')),
                ('order', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
