# Generated by Django 5.0 on 2025-07-28 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0009_howtwo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HowTwo',
            new_name='HowTo',
        ),
    ]
