[project]
name = "heliumos-website"
version = "0.1.0"
dependencies = [
    "django==5",
    "django-distill==3",
    "django-extensions==3"
]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"
